name: Java CI con Cucumber y GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar, ejecutar tests y generar reporte JaCoCo + Cucumber
        run: mvn clean test jacoco:report
      
      - name: Subir reporte JaCoCo como artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Subir reporte Cucumber como artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-report.html
        if-no-files-found: error

      - name: Copiar reporte Cucumber a carpeta "public"
        run: |
          mkdir -p public
          cp target/cucumber-report.html public/index.html

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

